name: Playwright CI + Azure Deployment

on:
  push:
    branches:
      - main

jobs:

  test-build-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Install dependencies
      run: npm install


    - name: Install Playwright browsers
      run: npx playwright install --with-deps


    - name: Run Playwright Tests
      run: npx playwright test


    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report


# -------------------------------
# Azure Login
# -------------------------------

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


# -------------------------------
# Docker Login to ACR
# -------------------------------

    - name: Login to Azure Container Registry
      run: |
        docker login ${{ secrets.ACR_LOGIN_SERVER }} \
        -u ${{ secrets.ACR_USERNAME }} \
        -p ${{ secrets.ACR_PASSWORD }}


# -------------------------------
# Build Docker Image
# -------------------------------

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/playwright-tests:${{ github.sha }} .


# -------------------------------
# Push Image to ACR
# -------------------------------

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/playwright-tests:${{ github.sha }}


# -------------------------------
# Deploy to Azure Container Apps
# -------------------------------

    - name: Deploy to Azure Container Apps
      run: |

        az containerapp update \
          --name playwright-runner \
          --resource-group rg-playwright \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/playwright-tests:${{ github.sha }}