name: Playwright CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  playwright-tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]

    steps:

# -------------------------------
# Checkout Code
# -------------------------------

    - name: Checkout repository
      uses: actions/checkout@v4


# -------------------------------
# Setup Node
# -------------------------------

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22


# -------------------------------
# Install Dependencies
# -------------------------------

    - name: Install dependencies
      run: npm ci


# -------------------------------
# Install Playwright Browsers
# -------------------------------

    - name: Install Playwright browsers
      run: npx playwright install --with-deps


# -------------------------------
# Run Tests
# -------------------------------

    - name: Run Playwright Tests
      run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=blob
      env:
        APP_URL: ${{ vars.APP_URL }}
        AUTH_SESSION: ${{ secrets.AUTH_SESSION }}


# -------------------------------
# Upload Blob Report
# -------------------------------

    - name: Upload Shard Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.shardIndex }}-${{ matrix.shardTotal }}
        path: blob-report
        if-no-files-found: warn


  merge-reports:

    if: always()
    needs: playwright-tests
    runs-on: ubuntu-latest

    steps:

# -------------------------------
# Checkout repository
# -------------------------------

    - name: Checkout repository
      uses: actions/checkout@v4


# -------------------------------
# Setup Node
# -------------------------------

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22


# -------------------------------
# Install dependencies
# -------------------------------

    - name: Install dependencies
      run: npm ci


# -------------------------------
# Download shard reports
# -------------------------------

    - name: Download Shard Reports
      uses: actions/download-artifact@v4
      with:
        path: all-blob-reports
        merge-multiple: true


# -------------------------------
# Merge Playwright reports
# -------------------------------

    - name: Merge Playwright Reports
      run: npx playwright merge-reports --reporter html ./all-blob-reports


# -------------------------------
# Upload final HTML report
# -------------------------------

    - name: Upload Final Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report

  deploy-report:

      needs: merge-reports
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
        contents: read

      steps:

      - name: Download Final Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

# name: Playwright CI

# on:
#   push:
#     branches:
#       - main

# jobs:

#   test-build-deploy:

#     runs-on: ubuntu-latest

#     steps:

# # -------------------------------
# # Checkout Code
# # -------------------------------

#     - name: Checkout repository
#       uses: actions/checkout@v4


# # -------------------------------
# # Setup Node
# # -------------------------------

#     - name: Setup Node
#       uses: actions/setup-node@v4
#       with:
#         node-version: 20


# # -------------------------------
# # Install Dependencies
# # -------------------------------

#     - name: Install dependencies
#       run: npm install


# # -------------------------------
# # Install Playwright Browsers
# # -------------------------------

#     - name: Install Playwright browsers
#       run: npx playwright install --with-deps


# # -------------------------------
# # Run Tests
# # -------------------------------

#     - name: Run Playwright Tests
#       run: npx playwright test


# # -------------------------------
# # Upload Test Report
# # -------------------------------

#     - name: Upload Test Report
#       uses: actions/upload-artifact@v4
#       with:
#         name: playwright-report
#         path: playwright-report


# # -------------------------------
# # Azure Login
# # -------------------------------

#     - name: Login to Azure
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}


# # -------------------------------
# # Ensure Resource Group Exists
# # -------------------------------

#     - name: Ensure Resource Group Exists
#       run: |
#         if az group show --name ${{ vars.RESOURCE_GROUP }} > /dev/null 2>&1; then
#           echo "Resource group exists"
#         else
#           echo "Creating resource group..."
#           az group create \
#             --name ${{ vars.RESOURCE_GROUP }} \
#             --location ${{ vars.LOCATION }}
#         fi


# # -------------------------------
# # Ensure ACR Exists
# # -------------------------------

#     - name: Ensure ACR Exists
#       run: |
#         if az acr show --name ${{ vars.ACR_NAME }} --resource-group ${{ vars.RESOURCE_GROUP }} > /dev/null 2>&1; then
#           echo "ACR already exists"
#         else
#           echo "Creating ACR..."
#           az acr create \
#             --name ${{ vars.ACR_NAME }} \
#             --resource-group ${{ vars.RESOURCE_GROUP }} \
#             --sku Basic \
#             --location ${{ vars.LOCATION }} \
#             --admin-enabled true
#         fi


# # -------------------------------
# # Login to ACR
# # -------------------------------

#     - name: Login to ACR
#       run: az acr login --name ${{ vars.ACR_NAME }}


# # -------------------------------
# # Ensure Container Apps Environment Exists
# # -------------------------------

#     - name: Ensure Container Apps Environment Exists
#       run: |
#         if az containerapp env show \
#           --name ${{ vars.CONTAINER_ENV_NAME }} \
#           --resource-group ${{ vars.RESOURCE_GROUP }} > /dev/null 2>&1; then
          
#           echo "Container Apps Environment exists"
          
#         else
          
#           echo "Creating Container Apps Environment..."
          
#           az containerapp env create \
#             --name ${{ vars.CONTAINER_ENV_NAME }} \
#             --resource-group ${{ vars.RESOURCE_GROUP }} \
#             --location ${{ vars.LOCATION }}
#         fi


# # -------------------------------
# # Build Docker Image
# # -------------------------------

#     - name: Build Docker Image
#       run: |
#         docker build -t ${{ vars.ACR_LOGIN_SERVER }}/playwright-tests:${{ github.sha }} .


# # -------------------------------
# # Push Docker Image
# # -------------------------------

#     - name: Push Docker Image
#       run: |
#         docker push ${{ vars.ACR_LOGIN_SERVER }}/playwright-tests:${{ github.sha }}


# # -------------------------------
# # Deploy Container App
# # -------------------------------

#     - name: Deploy Container App
#       run: |

#         if az containerapp show \
#           --name ${{ vars.CONTAINER_APP_NAME }} \
#           --resource-group ${{ vars.RESOURCE_GROUP }} > /dev/null 2>&1; then
          
#           echo "Container App exists. Updating image..."
          
#           az containerapp update \
#             --name ${{ vars.CONTAINER_APP_NAME }} \
#             --resource-group ${{ vars.RESOURCE_GROUP }} \
#             --image ${{ vars.ACR_LOGIN_SERVER }}/playwright-tests:${{ github.sha }}

#         else
          
#           echo "Container App does not exist. Creating..."
          
#           az containerapp create \
#             --name ${{ vars.CONTAINER_APP_NAME }} \
#             --resource-group ${{ vars.RESOURCE_GROUP }} \
#             --environment ${{ vars.CONTAINER_ENV_NAME }} \
#             --image ${{ vars.ACR_LOGIN_SERVER }}/playwright-tests:${{ github.sha }} \
#             --target-port 3000 \
#             --ingress external \
#             --registry-server ${{ vars.ACR_LOGIN_SERVER }}
#         fi